import { TestProject, LocalPlatformItem } from './types';

export const PLATFORM_URLS: Record<string, string> = {
  'ME': 'https://mech.hku.hk/mech_facility_charging/',
  'CHEM': 'https://www.chemistry.hku.hk/facilities/',
  '生命科学系': 'https://www.biosch.hku.hk/facilities/',
  'UCF': 'https://emunit.hku.hk/#/pages/home.php',
  'MILES': 'http://www.bynonco.com:8008/?XPath=000046',
  'CityU': 'https://ebooking1.mse.cityu.edu.hk/login/'
};

export const mockTestProjects: TestProject[] = [
  { 
    id: '1', 
    name: 'XPS (X-ray Photoelectron Spectroscopy / 光电子能谱)', 
    kuaiyicePrice: '90/样', 
    kuaiyiceDetail: '1、XPS普通测试费用：全谱+精细谱，3个元素90元(加含碳在内)，增加一个元素+30元，增加价带谱+50元，俄歇谱一个元素50元；只做价带谱VB-XPS：90元/样(只有价带谱和C谱的数据，其他没有元素谱)，磁性样品不加费用，默认是测最强轨道峰，如有其它轨道要求，请备注清楚（每个轨道按照一个元素计数）。 2、xps深度溅射收费 氩离子刻蚀：10nm内100元，超过后每增加10nm+40元； 团簇刻蚀：10nm内150元，超过后每增加10nm+50元； 3、XPS大尺度加收费用：高度小于10mm,直径5mm-10mm加收50元，直径10mm-20mm加收150元，直径20mm-30mm加收250元，直径30mm-40mm加收350元，直径40mm-50mm加收450元，直径40-60mm加收550元。 4、手套箱一批600元制样费（一批最多8个样，不满8个按80/样）。',
    compassPrice: '90/样', 
    compassDetail: '1、XPS普通测试费用：全谱+精细谱，3个元素90元(加含碳在内)，增加一个元素+30元，增加价带谱+50元，俄歇谱一个元素50元；只做价带谱VB-XPS：90元/样(只有价带谱和C谱的数据，其他没有元素谱)，磁性样品不加费用，默认是测最强轨道峰，如有其它轨道要求，请备注清楚（每个轨道按照一个元素计数）。 2、xps深度溅射收费 氩离子刻蚀：10nm内100元，超过后每增加10nm+40元； 团簇刻蚀：10nm内150元，超过后每增加10nm+50元； 3、XPS大尺度加收费用：高度小于10mm,直径5mm-10mm加收50元，直径10mm-20mm加收150元，直径20mm-30mm加收250元，直径30mm-40mm加收350元，直径40mm-50mm加收450元，直径40-60mm加收550元。 4、手套箱制样费：80元/样。',
    recommendation: '两家基础价相同 (90)', 
    hkuAvailable: true, 
    cityuAvailable: true, 
    milesAvailable: true, 
    mainlandAvailable: false, 
    remarks: '全谱+精细谱' 
  },
  { 
    id: '2', 
    name: 'UPS (Ultraviolet Photoelectron Spectroscopy / 紫外能谱)', 
    kuaiyicePrice: '360/样', 
    kuaiyiceDetail: '块体/薄膜样品360元/样，制样+100 清洁+50',
    compassPrice: '400/样', 
    compassDetail: '块体/薄膜样品400元/样，粉末需要制样加100元/样，氩单原子离子表面清洁加50元/样，氩团簇离子表面清洁加100元/样。',
    recommendation: '快易测 (360低于400)', 
    hkuAvailable: true, 
    cityuAvailable: false, 
    milesAvailable: false, 
    mainlandAvailable: false, 
    remarks: '功函数测试' 
  },
  { 
    id: '3', 
    name: 'XRD (X-ray Diffraction / 物相分析)', 
    kuaiyicePrice: '40/样', 
    kuaiyiceDetail: '常规广角测试 40元/样',
    compassPrice: '40/样', 
    compassDetail: '固体样品：常规铜靶测试：常规广角（10-80°或5-90°）：10°/min，40元/样；5°/min，60元/样；2°/min，100元/样；1°/min，200元/样；小角0.5-10°：1°/min，100元/样；0.5°/min，150元/样。 钴靶：≤15min ：200元/样；≤30min ：350元/样；≤60min ：500元/样；超过60min等特殊要求可以和当地项目经理沟通~',
    recommendation: '两家基础价相同 (40)', 
    hkuAvailable: true, 
    cityuAvailable: true, 
    milesAvailable: true, 
    mainlandAvailable: true, 
    remarks: '常规广角' 
  },
  { id: '4', name: 'Single Crystal XRD (单晶XRD)', kuaiyicePrice: '400/样', compassPrice: '350/样', recommendation: '科学指南针 (350低于400)', hkuAvailable: true, cityuAvailable: true, milesAvailable: false, mainlandAvailable: false, remarks: '小分子单晶' },
  { id: '5', name: 'XRF (X-ray Fluorescence / 荧光光谱)', kuaiyicePrice: '160/样', compassPrice: '160/样', recommendation: '两家基础价相同 (160)', hkuAvailable: false, cityuAvailable: false, milesAvailable: false, mainlandAvailable: false, remarks: '元素定量分析' },
  { id: '6', name: 'Raman Spectroscopy (拉曼光谱)', kuaiyicePrice: '100/样', compassPrice: '120/样', recommendation: '快易测 (100低于120)', hkuAvailable: true, cityuAvailable: true, milesAvailable: true, mainlandAvailable: false, remarks: '常规拉曼' },
  { id: '7', name: 'FTIR (Fourier Transform Infrared Spectroscopy / 红外)', kuaiyicePrice: '50/样', compassPrice: '90/样', recommendation: '快易测 (50低于90)', hkuAvailable: true, cityuAvailable: true, milesAvailable: true, mainlandAvailable: false, remarks: '溴化钾压片' },
  { id: '8', name: 'UV-Vis (Ultraviolet-Visible Spectroscopy / 紫外可见)', kuaiyicePrice: '100/样', compassPrice: '110/样', recommendation: '快易测 (100低于110)', hkuAvailable: true, cityuAvailable: true, milesAvailable: true, mainlandAvailable: false, remarks: '溶液/薄膜' },
  { id: '9', name: 'SEM (Scanning Electron Microscopy / 扫描电镜)', kuaiyicePrice: '90/样', compassPrice: '90/样', recommendation: '两家基础价相同 (90)', hkuAvailable: true, cityuAvailable: true, milesAvailable: true, mainlandAvailable: false, remarks: '形貌观察' },
  { id: '10', name: 'TEM (Transmission Electron Microscopy / 透射电镜)', kuaiyicePrice: '300/样', compassPrice: '350/样', recommendation: '快易测 (300低于350)', hkuAvailable: true, cityuAvailable: false, milesAvailable: true, mainlandAvailable: false, remarks: '高分辨形貌' },
  { id: '11', name: 'AFM (Atomic Force Microscopy / 原子力)', kuaiyicePrice: '270/样', compassPrice: '290/样', recommendation: '快易测 (270低于290)', hkuAvailable: true, cityuAvailable: true, milesAvailable: false, mainlandAvailable: false, remarks: '粗糙度/形貌' },
  { id: '12', name: 'FIB (Focused Ion Beam / 双束电镜)', kuaiyicePrice: '1200/h', compassPrice: '1200/h', recommendation: '两家同为1200/h', hkuAvailable: true, cityuAvailable: false, milesAvailable: false, mainlandAvailable: false, remarks: '剖面分析' },
  { id: '13', name: 'Cryo-TEM (Cryogenic Transmission Electron Microscopy / 冷冻电镜)', kuaiyicePrice: '1500/h', compassPrice: '1800/样', recommendation: '快易测 (1500/h)', hkuAvailable: false, cityuAvailable: false, milesAvailable: false, mainlandAvailable: false, remarks: '生物/敏感样品' },
  { id: '14', name: 'TOF-SIMS (Time-of-Flight Secondary Ion Mass Spectrometry)', kuaiyicePrice: '900/样', compassPrice: '900/样', recommendation: '两家基础价相同 (900)', hkuAvailable: false, cityuAvailable: false, milesAvailable: false, mainlandAvailable: false, remarks: '表面质谱分析' },
  { id: '15', name: 'GPC (Gel Permeation Chromatography / 凝胶色谱)', kuaiyicePrice: '360/样', compassPrice: '400/样', recommendation: '快易测 (360低于400)', hkuAvailable: false, cityuAvailable: false, milesAvailable: true, mainlandAvailable: false, remarks: '分子量分布' },
  { id: '16', name: 'HPLC (High Performance Liquid Chromatography / 液相色谱)', kuaiyicePrice: '100/样', compassPrice: '150/样', recommendation: '快易测 (100低于150)', hkuAvailable: false, cityuAvailable: false, milesAvailable: true, mainlandAvailable: false, remarks: '常规分析' },
  { id: '17', name: 'GC (Gas Chromatography / 气相色谱)', kuaiyicePrice: '100/样', compassPrice: '150/样', recommendation: '快易测 (100低于150)', hkuAvailable: false, cityuAvailable: false, milesAvailable: true, mainlandAvailable: false, remarks: '挥发性成分' },
  { id: '18', name: 'GC-MS (Gas Chromatography-Mass Spectrometry / 气质联用)', kuaiyicePrice: '250/样', compassPrice: '300/样', recommendation: '快易测 (250低于300)', hkuAvailable: false, cityuAvailable: false, milesAvailable: false, mainlandAvailable: false, remarks: '定性定量' },
  { id: '19', name: 'LC-MS (Liquid Chromatography-Mass Spectrometry / 液质联用)', kuaiyicePrice: '350/样', compassPrice: '550/样', recommendation: '快易测 (350低于550)', hkuAvailable: false, cityuAvailable: false, milesAvailable: true, mainlandAvailable: false, remarks: '高灵敏度' },
  { id: '20', name: 'ICP-MS (Inductively Coupled Plasma Mass Spectrometry / 质谱)', kuaiyicePrice: '60/样', compassPrice: '530/样', recommendation: '快易测 (60低于530)', hkuAvailable: true, cityuAvailable: false, milesAvailable: false, mainlandAvailable: false, remarks: '微量元素' },
  { id: '21', name: 'ICP-OES (Inductively Coupled Plasma Optical Emission Spectroscopy / 发射光谱)', kuaiyicePrice: '60/样', compassPrice: '530/样', recommendation: '快易测 (60低于530)', hkuAvailable: true, cityuAvailable: false, milesAvailable: true, mainlandAvailable: false, remarks: '常量元素' },
  { id: '22', name: 'Liquid NMR (Liquid Nuclear Magnetic Resonance / 液体核磁)', kuaiyicePrice: '40/样', compassPrice: '40/样', recommendation: '两家基础价相同 (40)', hkuAvailable: true, cityuAvailable: false, milesAvailable: true, mainlandAvailable: false, remarks: '1H/13C' },
  { id: '23', name: 'Solid NMR (Solid Nuclear Magnetic Resonance / 固体核磁)', kuaiyicePrice: '300/样', compassPrice: '300/样', recommendation: '两家基础价相同 (300)', hkuAvailable: true, cityuAvailable: false, milesAvailable: false, mainlandAvailable: false, remarks: '一维谱' },
  { id: '24', name: 'SAXS/WAXS (Small/Wide Angle X-ray Scattering)', kuaiyicePrice: '500/样', compassPrice: '600/样', recommendation: '快易测 (500低于600)', hkuAvailable: true, cityuAvailable: false, milesAvailable: false, mainlandAvailable: false, remarks: '小角散射' },
  { id: '25', name: 'EPR (Electron Paramagnetic Resonance / 顺磁)', kuaiyicePrice: '360/样', compassPrice: '400/样', recommendation: '快易测 (360低于400)', hkuAvailable: false, cityuAvailable: false, milesAvailable: false, mainlandAvailable: false, remarks: '自由基检测' },
  { id: '26', name: 'BET (Brunauer-Emmett-Teller / 比表面积)', kuaiyicePrice: '100/样', compassPrice: '100/样', recommendation: '两家基础价相同 (100)', hkuAvailable: true, cityuAvailable: false, milesAvailable: false, mainlandAvailable: false, remarks: '氮气吸附' },
  { id: '27', name: 'MIP (Mercury Intrusion Porosimetry / 压汞)', kuaiyicePrice: '450/样', compassPrice: '550/样', recommendation: '快易测 (450低于550)', hkuAvailable: false, cityuAvailable: false, milesAvailable: false, mainlandAvailable: false, remarks: '孔径分布' },
  { id: '28', name: 'TPD/TPR (Temperature Programmed Desorption/Reduction)', kuaiyicePrice: '240/样', compassPrice: '240/样', recommendation: '两家基础价相同 (240)', hkuAvailable: false, cityuAvailable: false, milesAvailable: false, mainlandAvailable: false, remarks: '程序升温' },
  { id: '29', name: 'TGA (Thermogravimetric Analysis / 热重)', kuaiyicePrice: '120/h', compassPrice: '120/h', recommendation: '两家基础价相同 (120)', hkuAvailable: true, cityuAvailable: true, milesAvailable: true, mainlandAvailable: false, remarks: '热稳定性' },
  { id: '30', name: 'DSC (Differential Scanning Calorimetry / 差示扫描量热)', kuaiyicePrice: '120/h', compassPrice: '1000/样', recommendation: '快易测 (120低于1000)', hkuAvailable: true, cityuAvailable: true, milesAvailable: false, mainlandAvailable: false, remarks: '相变温度' },
  { id: '31', name: 'TG-DSC (Simultaneous Thermal Analysis / 同步热分析)', kuaiyicePrice: '150/h', compassPrice: '150/h', recommendation: '两家基础价相同 (150)', hkuAvailable: false, cityuAvailable: true, milesAvailable: false, mainlandAvailable: false, remarks: '同步热分析' },
  { id: '32', name: 'TG-MS (TGA-Mass Spectrometry / 热重质谱联用)', kuaiyicePrice: '550/样', compassPrice: '600/样', recommendation: '快易测 (550低于600)', hkuAvailable: false, cityuAvailable: false, milesAvailable: false, mainlandAvailable: false, remarks: '热重质谱联用' },
  { id: '33', name: 'TG-IR (TGA-Infrared Spectroscopy / 热重红外联用)', kuaiyicePrice: '550/样', compassPrice: '600/样', recommendation: '快易测 (550低于600)', hkuAvailable: false, cityuAvailable: false, milesAvailable: false, mainlandAvailable: false, remarks: '热重红外联用' },
  { id: '34', name: 'DMA (Dynamic Mechanical Analysis / 动态热机械)', kuaiyicePrice: '350/样', compassPrice: '350/样', recommendation: '两家基础价相同 (350)', hkuAvailable: false, cityuAvailable: false, milesAvailable: false, mainlandAvailable: false, remarks: '动态热机械' },
  { id: '35', name: 'HotDisk (Thermal Conductivity / 导热系数)', kuaiyicePrice: '400/样', compassPrice: '400/样', recommendation: '两家基础价相同 (400)', hkuAvailable: false, cityuAvailable: false, milesAvailable: false, mainlandAvailable: false, remarks: '导热系数' },
  { id: '36', name: 'LFA (Laser Flash Analysis / 激光导热)', kuaiyicePrice: '250/样', compassPrice: '300/样', recommendation: '快易测 (250低于300)', hkuAvailable: false, cityuAvailable: false, milesAvailable: false, mainlandAvailable: false, remarks: '激光导热' },
  { id: '37', name: 'Contact Angle (接触角)', kuaiyicePrice: '50/样', compassPrice: '60/样', recommendation: '快易测 (50低于60)', hkuAvailable: true, cityuAvailable: true, milesAvailable: false, mainlandAvailable: false, remarks: '亲疏水性' },
  { id: '38', name: 'Laser Particle Size Analysis (激光粒度)', kuaiyicePrice: '100/样', compassPrice: '130/样', recommendation: '快易测 (100低于130)', hkuAvailable: false, cityuAvailable: false, milesAvailable: false, mainlandAvailable: false, remarks: '粒径分布' },
  { id: '39', name: 'Zeta Potential (Zeta 电位)', kuaiyicePrice: '100/样', compassPrice: '140/样', recommendation: '快易测 (100低于140)', hkuAvailable: true, cityuAvailable: false, milesAvailable: true, mainlandAvailable: false, remarks: '胶体稳定性' },
  { id: '40', name: 'TOC (Total Organic Carbon / 总有机碳)', kuaiyicePrice: '70/样', compassPrice: '70/样', recommendation: '两家首测同为70', hkuAvailable: false, cityuAvailable: false, milesAvailable: false, mainlandAvailable: false, remarks: '总有机碳' },
  { id: '41', name: 'CHNS (Elemental Analysis / 元素分析)', kuaiyicePrice: '160/样', compassPrice: '180/样', recommendation: '快易测 (160低于180)', hkuAvailable: false, cityuAvailable: false, milesAvailable: false, mainlandAvailable: false, remarks: '元素分析' },
  { id: '42', name: 'Electrochemical Workstation (电化学工作站)', kuaiyicePrice: '100/样', compassPrice: '100/样', recommendation: '两家基础价相同 (100)', hkuAvailable: false, cityuAvailable: false, milesAvailable: true, mainlandAvailable: false, remarks: 'CV/EIS' },
  { id: '43', name: 'EBSD (Electron Backscatter Diffraction / 晶体取向)', kuaiyicePrice: '600/区域', compassPrice: '600/区域', recommendation: '两家基础价相同 (600)', hkuAvailable: false, cityuAvailable: false, milesAvailable: false, mainlandAvailable: false, remarks: '晶体取向' },
  { id: '44', name: 'CP (Cross-section Polishing / 离子研磨)', kuaiyicePrice: '900/样', compassPrice: '1200/样', recommendation: '快易测 (900低于1200)', hkuAvailable: false, cityuAvailable: false, milesAvailable: false, mainlandAvailable: false, remarks: '氩离子抛光' },
  { id: '45', name: 'CLSM (Confocal Laser Scanning Microscopy / 共聚焦)', kuaiyicePrice: '300/样', compassPrice: '300/样', recommendation: '两家基础价相同 (300)', hkuAvailable: false, cityuAvailable: false, milesAvailable: false, mainlandAvailable: false, remarks: '激光共聚焦' },
  { id: '46', name: 'In-situ Raman (Variable Temp / 原位拉曼-变温)', kuaiyicePrice: '400/h', compassPrice: '400/h', recommendation: '科学指南针 (400/h更低)', hkuAvailable: false, cityuAvailable: false, milesAvailable: false, mainlandAvailable: false, remarks: '变温+气氛' },
  { id: '47', name: 'In-situ Raman (Electrocatalysis / 原位拉曼-电催化)', kuaiyicePrice: '3500/样', compassPrice: '4000/样', recommendation: '快易测 (3500低于4000)', hkuAvailable: false, cityuAvailable: false, milesAvailable: false, mainlandAvailable: false, remarks: '电化学原位' },
  { id: '48', name: 'In-situ FTIR (原位红外)', kuaiyicePrice: '2300/样', compassPrice: '4500/样', recommendation: '快易测 (2300低于4500)', hkuAvailable: false, cityuAvailable: false, milesAvailable: false, mainlandAvailable: false, remarks: '原位电催化' },
  { id: '49', name: 'Synchrotron Radiation (同步辐射)', kuaiyicePrice: '2500/元素', compassPrice: '3500/元素', recommendation: '快易测 (2500低于3500)', hkuAvailable: false, cityuAvailable: false, milesAvailable: false, mainlandAvailable: false, remarks: 'XAFS/SAXS' },
  { id: '50', name: 'In-situ XRD (原位XRD)', kuaiyicePrice: '500/h', compassPrice: '0', recommendation: '快易测 (500/h)', hkuAvailable: false, cityuAvailable: false, milesAvailable: false, mainlandAvailable: false, remarks: '指南针无法测试' },
  { id: '51', name: 'In-situ XPS (Variable Temp / 原位XPS-变温)', kuaiyicePrice: '700/样', compassPrice: '800/样', recommendation: '快易测 (700低于800)', hkuAvailable: false, cityuAvailable: false, milesAvailable: false, mainlandAvailable: false, remarks: '变温+气氛' },
  { id: '52', name: 'In-situ XPS (Electrochemical / 原位XPS-电化学)', kuaiyicePrice: '900/样', compassPrice: '0', recommendation: '快易测 (按项目询价)', hkuAvailable: false, cityuAvailable: false, milesAvailable: false, mainlandAvailable: false, remarks: '指南针无法测试' },
  { id: '53', name: 'Optical Microscope (光学显微镜)', kuaiyicePrice: '30/样', compassPrice: '50/样', recommendation: '快易测 (30)', hkuAvailable: true, cityuAvailable: true, milesAvailable: false, mainlandAvailable: false, remarks: '形貌观察' },
  { id: '54', name: 'UTM (Universal Testing Machine / 万能试验机)', kuaiyicePrice: '150/样', compassPrice: '200/样', recommendation: '快易测 (150)', hkuAvailable: true, cityuAvailable: true, milesAvailable: false, mainlandAvailable: false, remarks: '拉伸/压缩' },
];

export const mockLocalItems: LocalPlatformItem[] = [
  // ME Platform
  { id: 'me1', name: 'SEM (Scanning Electron Microscopy / 扫描电镜)', platform: 'ME', instrumentName: 'Zeiss Sigma 300/360', hkuUserFee: '120 HKD/h', billingMethod: '按小时', remarks: '培训-自测' },
  { id: 'me2', name: 'XRD (X-ray Diffraction / 物相分析)', platform: 'ME', instrumentName: 'Rigaku SmartLab 9kW', hkuUserFee: '120 HKD/h', billingMethod: '按小时', remarks: '培训-自测' },
  { id: 'me3', name: 'AFM (Atomic Force Microscopy / 原子力显微镜)', platform: 'ME', instrumentName: 'Bruker MultiMode 8', hkuUserFee: '240 HKD/h', billingMethod: '按小时', remarks: '培训-自测' },
  { id: 'me4', name: 'TGA (Thermogravimetric Analysis / 热重分析)', platform: 'ME', instrumentName: 'Setaram Labsys Evo', hkuUserFee: '60 HKD/h', billingMethod: '按小时', remarks: '培训-自测' },
  { id: 'me5', name: 'Optical Profiler (光学轮廓仪)', platform: 'ME', instrumentName: 'Bruker Contour GT-K', hkuUserFee: '120 HKD/h', billingMethod: '按小时', remarks: '培训-自测' },
  { id: 'me6', name: 'Optical Microscope (光学显微镜)', platform: 'ME', instrumentName: 'Zeiss Axioscope5', hkuUserFee: '60 HKD/h', billingMethod: '按小时', remarks: '培训-自测' },
  { id: 'me7', name: 'UV-Vis (Ultraviolet-Visible Spectroscopy / 紫外可见光谱)', platform: 'ME', instrumentName: 'LAMBDA 365', hkuUserFee: '60 HKD/h', billingMethod: '按小时', remarks: '培训-自测' },
  { id: 'me8', name: 'Contact Angle (接触角测量仪)', platform: 'ME', instrumentName: 'Sindatek 100SB', hkuUserFee: '60 HKD/h', billingMethod: '按小时', remarks: '培训-自测' },
  { id: 'me9', name: 'APT (Atom Probe Tomography / 原子探针)', platform: 'ME', instrumentName: 'Cameca LEAP 6000', hkuUserFee: '500 HKD/h', billingMethod: '按小时', remarks: '培训-自测' },
  { id: 'me10', name: 'ALD (Atomic Layer Deposition / 原子层沉积)', platform: 'ME', instrumentName: 'Atomic Layer Deposition', hkuUserFee: '360 HKD/h', billingMethod: '按小时', remarks: '培训-自测' },
  { id: 'me11', name: 'PLD (Pulsed Laser Deposition / 脉冲激光沉积)', platform: 'ME', instrumentName: 'Pulse Laser Deposition', hkuUserFee: '360 HKD/h', billingMethod: '按小时', remarks: '4 hours/session' },
  { id: 'me12', name: 'Raman/PL (Raman/Photoluminescence / 拉曼/荧光)', platform: 'ME', instrumentName: 'Confocal Raman', hkuUserFee: '60 HKD/h', billingMethod: '按小时', remarks: '培训-自测' },
  { id: 'me13', name: 'PVD (Physical Vapor Deposition / 物理气相沉积)', platform: 'ME', instrumentName: 'PVD thermal deposition', hkuUserFee: '180 HKD/h', billingMethod: '按小时', remarks: '不含耗材' },
  { id: 'me14', name: 'LED Lithography (LED 光刻)', platform: 'ME', instrumentName: 'LED lithography', hkuUserFee: '300 HKD/h', billingMethod: '按小时', remarks: '培训-自测' },
  { id: 'me15', name: 'Probe Station (探针台)', platform: 'ME', instrumentName: 'Probe station', hkuUserFee: '180 HKD/h', billingMethod: '按小时', remarks: '不含耗材' },
  
  // CHEM Platform
  { id: 'ch1', name: 'FTIR (Fourier Transform Infrared Spectroscopy / 红外光谱)', platform: 'CHEM', instrumentName: '傅里叶变换红外', hkuUserFee: '200 HKD/h', billingMethod: '按小时', remarks: '培训-自测' },
  { id: 'ch2', name: 'Liquid NMR (Liquid Nuclear Magnetic Resonance / 液体核磁)', platform: 'CHEM', instrumentName: '核磁共振 (液体)', hkuUserFee: '100 HKD/h', billingMethod: '按小时', remarks: '培训-自测' },
  { id: 'ch3', name: 'Solid NMR (Solid Nuclear Magnetic Resonance / 固体核磁)', platform: 'CHEM', instrumentName: '核磁共振 (固体)', hkuUserFee: '100 HKD/h', billingMethod: '按小时', remarks: '送样' },
  { id: 'ch4', name: 'Zeta Potential (Zeta 电位)', platform: 'CHEM', instrumentName: 'Zeta电位分析', hkuUserFee: '180 HKD/h', billingMethod: '按小时', remarks: '培训-自测' },
  { id: 'ch5', name: 'XPS (X-ray Photoelectron Spectroscopy / 光电子能谱)', platform: 'CHEM', instrumentName: 'XPS', hkuUserFee: '200 HKD/h', billingMethod: '按小时', remarks: '送样' },

  // 生命科学系
  { id: 'ls1', name: 'ICP-MS (Inductively Coupled Plasma Mass Spectrometry / 质谱)', platform: '生命科学系', instrumentName: '电感耦合等离子体质谱', hkuUserFee: '300 HKD/h', billingMethod: '按小时', remarks: '培训-自测' },
  { id: 'ls2', name: 'ICP-OES (Inductively Coupled Plasma Optical Emission Spectroscopy / 发射光谱)', platform: '生命科学系', instrumentName: '电感耦合等离子体发射', hkuUserFee: '300 HKD/h', billingMethod: '按小时', remarks: '培训-自测' },

  // UCF Platform
  { id: 'ucf1', name: 'Profiler (轮廓仪)', platform: 'UCF', instrumentName: 'KLA Alpha-Step D-600', hkuUserFee: '120 HKD/h', billingMethod: '按小时', remarks: '1 hour minimum' },
  { id: 'ucf2', name: 'Sputter (溅射仪)', platform: 'UCF', instrumentName: 'Kurt J. Lesker Mini', hkuUserFee: '180 HKD/h', billingMethod: '按小时', remarks: '1 hour minimum' },
  { id: 'ucf3', name: 'E-Beam (电子束蒸发)', platform: 'UCF', instrumentName: 'Kurt J. Lesker Mini', hkuUserFee: '180 HKD/h', billingMethod: '按小时', remarks: '1 hour minimum' },
  { id: 'ucf4', name: 'Thermal Evaporator (热蒸发)', platform: 'UCF', instrumentName: 'Kurt J. Lesker Mini', hkuUserFee: '180 HKD/h', billingMethod: '按小时', remarks: '1 hour minimum' },
  { id: 'ucf5', name: 'ALD (Atomic Layer Deposition / 原子层沉积)', platform: 'UCF', instrumentName: 'Kurt J. Lesker 150LE', hkuUserFee: '180 HKD/h', billingMethod: '按小时', remarks: '1 hour minimum' },
  { id: 'ucf6', name: 'ICP Etching (ICP 刻蚀)', platform: 'UCF', instrumentName: 'Oxford PlasmaPro 100', hkuUserFee: '300 HKD/h', billingMethod: '按小时', remarks: '1 hour minimum' },
  { id: 'ucf7', name: 'IBE (Ion Beam Etching / 离子束刻蚀)', platform: 'UCF', instrumentName: 'Elionix EIS-220P', hkuUserFee: '180 HKD/h', billingMethod: '按小时', remarks: '1 hour minimum' },
  { id: 'ucf8', name: 'Laser Lithography (激光光刻)', platform: 'UCF', instrumentName: 'Raith PicoMaster 200', hkuUserFee: '300 HKD/h', billingMethod: '按小时', remarks: '1 hour minimum' },
  { id: 'ucf9', name: 'Mask Aligner (光刻机)', platform: 'UCF', instrumentName: 'SUSS MA/BA6 Gen4', hkuUserFee: '300 HKD/h', billingMethod: '按小时', remarks: '1 hour minimum' },
  { id: 'ucf10', name: 'FIB-SEM (Focused Ion Beam Scanning Electron Microscopy / 双束电镜)', platform: 'UCF', instrumentName: 'Thermo Helios 5 CX', hkuUserFee: '450 HKD/h', billingMethod: '按小时', remarks: '1.5 hours/session' },
  { id: 'ucf11', name: 'FEG SEM (Field Emission Gun SEM / 场发射扫描电镜)', platform: 'UCF', instrumentName: 'Zeiss Sigma 300 VP', hkuUserFee: '150 HKD/h', billingMethod: '按小时', remarks: '0.5 hour minimum' },
  { id: 'ucf12', name: 'SEM (Scanning Electron Microscopy / 扫描电镜)', platform: 'UCF', instrumentName: 'Leo 1530 FEG', hkuUserFee: '150 HKD/h', billingMethod: '按小时', remarks: '1.5 hours/session' },
  { id: 'ucf13', name: 'FIB (Focused Ion Beam / 聚焦离子束)', platform: 'UCF', instrumentName: 'FEI Quanta 200 3D', hkuUserFee: '300 HKD/h', billingMethod: '按小时', remarks: '1.5 hours/session' },
  { id: 'ucf14', name: 'TEM/STEM (Transmission Electron Microscopy / 透射电镜)', platform: 'UCF', instrumentName: 'Thermo Talos F200X', hkuUserFee: '300 HKD/h', billingMethod: '按小时', remarks: '1.5 hours/session' },
  { id: 'ucf15', name: 'ETEM (Environmental TEM / 环境透射电镜)', platform: 'UCF', instrumentName: 'Thermo Themis ETEM', hkuUserFee: '300 HKD/h', billingMethod: '按小时', remarks: '1.5 hours/session' },
  { id: 'ucf16', name: 'XPS (X-ray Photoelectron Spectroscopy / 光电子能谱)', platform: 'UCF', instrumentName: 'Thermo Escalab QXi', hkuUserFee: '300 HKD/h', billingMethod: '按小时', remarks: '1 hour minimum' },
  { id: 'ucf17', name: 'TEM Mill (TEM 样品制备)', platform: 'UCF', instrumentName: 'Fischione Model 1051', hkuUserFee: '190 HKD/h', billingMethod: '按小时', remarks: '1 hour minimum' },
  { id: 'ucf18', name: 'SEM Mill (SEM 样品制备)', platform: 'UCF', instrumentName: 'Fischione Model 1061', hkuUserFee: '190 HKD/h', billingMethod: '按小时', remarks: '0.5 hour minimum' },
  { id: 'ucf19', name: 'Scanning TEM (扫描透射电镜)', platform: 'UCF', instrumentName: 'FEI Tecnai G2 20', hkuUserFee: '150 HKD/h', billingMethod: '按小时', remarks: '1.5 hours/session' },
  { id: 'ucf20', name: 'TEM (Transmission Electron Microscopy / 透射电镜)', platform: 'UCF', instrumentName: 'Philips CM100', hkuUserFee: '120 HKD/h', billingMethod: '按小时', remarks: '1.5 hours/session' },
  { id: 'ucf21', name: 'VP SEM (Variable Pressure SEM / 变压扫描电镜)', platform: 'UCF', instrumentName: 'Hitachi S3400N', hkuUserFee: '120 HKD/h', billingMethod: '按小时', remarks: '1.5 hours/session' },
  { id: 'ucf22', name: 's-SNOM / Nano-FTIR (近场光学显微镜)', platform: 'UCF', instrumentName: 'Neaspec IR-neaSCOPE', hkuUserFee: '150 HKD/h', billingMethod: '按小时', remarks: '1 hour minimum' },
  { id: 'ucf23', name: 'AFM-Raman / TERS (原子力拉曼)', platform: 'UCF', instrumentName: 'Horiba LabRAM Nano', hkuUserFee: '100 HKD/h', billingMethod: '按小时', remarks: '1 hour minimum' },
  { id: 'ucf24', name: 'AFM (Atomic Force Microscopy / 原子力显微镜)', platform: 'UCF', instrumentName: 'Bruker JPK NanoRacer', hkuUserFee: '150 HKD/h', billingMethod: '按小时', remarks: '1 hour minimum' },
  { id: 'ucf25', name: 'DSC (Differential Scanning Calorimetry / 差示扫描量热)', platform: 'UCF', instrumentName: 'Netzsch DSC 214', hkuUserFee: '60 HKD/h', billingMethod: '按小时', remarks: '1 hour minimum' },
  { id: 'ucf26', name: 'BET (Brunauer-Emmett-Teller / 比表面积)', platform: 'UCF', instrumentName: 'Micrometritics ASAP 2020', hkuUserFee: '60 HKD/h', billingMethod: '按小时', remarks: '10 hours minimum' },
  { id: 'ucf27', name: 'APT (Atom Probe Tomography / 原子探针)', platform: 'UCF', instrumentName: 'Cameca LEAP 6000', hkuUserFee: '500 HKD/h', billingMethod: '按小时', remarks: '1 hour minimum' },
  { id: 'ucf28', name: 'Ellipsometer (椭偏仪)', platform: 'UCF', instrumentName: 'J A Woollam RC2', hkuUserFee: '150 HKD/h', billingMethod: '按小时', remarks: '1 hour minimum' },
  { id: 'ucf29', name: 'UV-Vis-NIR (紫外可见近红外)', platform: 'UCF', instrumentName: 'Agilent Cary 5000', hkuUserFee: '150 HKD/h', billingMethod: '按小时', remarks: '1 hour minimum' },
  { id: 'ucf30', name: 'PL (Photoluminescence / 荧光光谱)', platform: 'UCF', instrumentName: 'Edinburgh FLS1000', hkuUserFee: '100 HKD/h', billingMethod: '按小时', remarks: '1 hour minimum' },
  { id: 'ucf31', name: 'SAXS (Small Angle X-ray Scattering / 小角散射)', platform: 'UCF', instrumentName: 'Xenocs Xeuss 3.0', hkuUserFee: '300 HKD/h', billingMethod: '按小时', remarks: '1.5 hours/session' },
  { id: 'ucf32', name: 'SC-XRD (Single Crystal XRD / 单晶衍射)', platform: 'UCF', instrumentName: 'Bruker D8 VENTURE', hkuUserFee: '100 HKD/h', billingMethod: '按小时', remarks: '4 hours/sample' },
  
  // MILES Platform
  { id: 'miles1', name: 'SEM (Scanning Electron Microscopy / 扫描电镜)', platform: 'MILES', instrumentName: 'MILES SEM', hkuUserFee: '150 HKD/样', billingMethod: '按样', remarks: '外测服务' },
  { id: 'miles2', name: 'XRD (X-ray Diffraction / 物相分析)', platform: 'MILES', instrumentName: 'MILES XRD', hkuUserFee: '100 HKD/样', billingMethod: '按样', remarks: '外测服务' },

  // CityU Platform
  { id: 'cityu1', name: 'SEM (Scanning Electron Microscopy / 扫描电镜)', platform: 'CityU', instrumentName: 'Thermo Fisher Apreo 2', hkuUserFee: '100 HKD/h', billingMethod: '2 h/session', remarks: 'MSE' },
  { id: 'cityu2', name: 'XPS (X-ray Photoelectron Spectroscopy / 光电子能谱)', platform: 'CityU', instrumentName: 'Thermo Fisher ESCALAB XI+', hkuUserFee: '340 HKD/h', billingMethod: '2 h/session', remarks: 'MSE' },
  { id: 'cityu3', name: 'XRD (桌面X射线衍射)', platform: 'CityU', instrumentName: 'D2 PHASER XE-T', hkuUserFee: '50 HKD/h', billingMethod: '0.5 h/session', remarks: 'MSE' },
  { id: 'cityu4', name: 'XRD (X射线衍射)', platform: 'CityU', instrumentName: 'Rigaku SmartLab 9kW', hkuUserFee: '95 HKD/h', billingMethod: '0.5 h/session', remarks: 'MSE' },
  { id: 'cityu5', name: 'AFM (Atomic Force Microscopy / 原子力显微镜)', platform: 'CityU', instrumentName: 'Bruker AFM System', hkuUserFee: '120 HKD/h', billingMethod: '0.5 h/session', remarks: 'MSE' },
  { id: 'cityu6', name: 'TGA (热重分析)', platform: 'CityU', instrumentName: 'PerkinElmer STA 6000', hkuUserFee: '-', billingMethod: '0.5 h/session', remarks: 'MSE' },
  { id: 'cityu7', name: 'Optical Microscope (光学显微镜)', platform: 'CityU', instrumentName: 'PerkinElmer (OM)', hkuUserFee: 'Free', billingMethod: '0.5 h/session', remarks: 'MSE' },
  { id: 'cityu8', name: 'UV-Vis (紫外可见光谱)', platform: 'CityU', instrumentName: 'Hitachi UH4150', hkuUserFee: '25 HKD/h', billingMethod: '0.5 h/session', remarks: 'MSE' },
  { id: 'cityu9', name: 'Contact Angle (接触角测量仪)', platform: 'CityU', instrumentName: 'DataPhysics', hkuUserFee: '300 HKD/h', billingMethod: '0.5 h/session', remarks: 'MSE' },
  { id: 'cityu10', name: 'FTIR (傅里叶变换红外光谱)', platform: 'CityU', instrumentName: 'PerkinElmer FTIR', hkuUserFee: '10 HKD/h', billingMethod: '0.5 h/session', remarks: 'MSE' },
  { id: 'cityu11', name: 'DSC (差示扫描量热)', platform: 'CityU', instrumentName: 'PerkinElmer DSC 8000', hkuUserFee: '30 HKD/h', billingMethod: '0.5 h/session', remarks: 'MSE' },
  { id: 'cityu12', name: 'Raman (拉曼光谱)', platform: 'CityU', instrumentName: 'WITec alpha300 R', hkuUserFee: '60 HKD/h', billingMethod: '0.5 h/session', remarks: 'MSE' },
  { id: 'cityu13', name: 'Single Crystal XRD (单晶X射线衍射)', platform: 'CityU', instrumentName: 'Rigaku X-ray Single Crystal', hkuUserFee: '-', billingMethod: '0.5 h/session', remarks: 'MSE' },
  { id: 'cityu14', name: 'UTM (物理性能测试)', platform: 'CityU', instrumentName: 'Instron Series 3382', hkuUserFee: '40 HKD/h', billingMethod: '0.5 h/session', remarks: 'MSE' },
  { id: 'cityu15', name: 'Electro-chemical Mass spectrometry', platform: 'CityU', instrumentName: '-', hkuUserFee: '-', billingMethod: '0.5 h/session', remarks: 'MSE' },
];
